### ISSUE TITLE
Sanitize point order for all honeybee models

### ISSUE THREAD

**Issue by cdriesler** [ladybug-tools/spider-2020#16]
Honeybee models provided with inconsistent (or even out of order) point data do not render correctly with the current three.js geometry creation routine. Concave shapes appear to be especially stubborn, but this might end up being a separate issue.

Per earlier discussion - sounds like the best move is to validate/sanitize point order for incoming honeybee geometry in the viewer itself. (Instead of expecting it to be right.)

@theo-armour pointed out that this should be possible with the ShapeUtils that ship with recent versions of three.js. The `.isClockwise` method, mixed with a good existing [clockwise point ordering algorithm](https://stackoverflow.com/questions/45660743/sort-points-in-counter-clockwise-in-javascript), makes a believable fix for a solution.

I plan to circle back with a solution in a few days. Wanted to open this up to get discussion going on any other strategies.

**Comment by theo-armour** [comment]
@cdriesler 

In recent version of the Spider gbXML Viewer I have reverted to the the Three.js ShapeUtils.triangulateShape method instead of new Shape.  The former is most difficult to set up but has the advantage of having been seen too generate inumerable renderings that appear to have no errors.

The current Spider Pollination Viewer (SPV) is suited to large modules with many thousands of faces where loading speed and low latency are of the essence and the occasional mis-drawn face is not a critical issue.

The downside to current Shape implementation in SPV is that in order to achieve speed face data is tightly bundled into high speed integer arrays which means displaying just a few individual spaces or stories will requires some heavy lifting in order to be implemented.

Future forks of the SPV could implement the traiangulatShape method and revert to faces being bundled into individual polygons.

***

BTW, I looked at these two files - uploaded by Mostapha:

* https://github.com/ladybug-tools/3d-models/blob/master/pollination/2020-08-21-revit-sample-files/2020_rac_advanced_sample_project.json
* https://github.com/ladybug-tools/3d-models/blob/master/pollination/2020-08-21-revit-sample-files/2020_rac_advanced_sample_project_sorted_points.json

The data handling of the files is of such a difference that I cannot even begin to wonder how to compare the issues.  ;-(

**Comment by mostaphaRoudsari** [comment]
Hi @theo-armour, sorry if the other model has too much going on. I created a single room model that shows two problems that we currently have in the viewer. It's a single corridor. The model should look like this:

![image](https://user-images.githubusercontent.com/2915573/92313690-898edf80-ef9c-11ea-93a6-6e9e103fa8e5.png)

But if you open it in the viewer as is, it will look like this.

![image](https://user-images.githubusercontent.com/2915573/92313722-cc50b780-ef9c-11ea-90cb-8eca47cfc1b5.png)

As you can see the windows are missing and the roof is not showing correctly. After sorting the vertices the windows will show up but the roof still doesn't render correctly.

![image](https://user-images.githubusercontent.com/2915573/92313748-16399d80-ef9d-11ea-8ec4-0de9ce1f3c74.png)

I'm attaching 3 different files in this zip file:

* corridor.hbjson: the original file as exported from Revit.
* corridor_fixed.hbjson: the same file but with vertices sorted using honeybee algorithms.
* corridor.3dm: a Rhino model which you can view [here](https://mcneel.github.io/rview/#/) which should give you a better idea of how the geometry should look like.

I change the face's display name to `Wall with openings` so it is easier to find. The apertures are named `Aperture 0`, `Aperture 1` and `Aperture 2`.

I hope this model can be helpful to find the root of the problem.

[corridor.zip](https://github.com/ladybug-tools/spider-2020/files/5178684/corridor.zip)

**Comment by cdriesler** [comment]
Resolved! Thank you for [the reference](https://github.com/ladybug-tools/spider-2020/blob/master/lib/gbxml/gbx-gbxml-parse-2020-10-09.js#L100-L165) Theo.

**Comment by theo-armour** [comment]
Nice!
